### ISSUE TITLE
Library is incompatible with Unity 2020

### ISSUE THREAD

**Issue by razenpok** [FreyaHolmer/Mathfs#6]
The code uses modern C# 9.0 features which are not available on Unity 2020 (which is the current LTS). Do you want:
- it to be Unity 2021+ compatible, or
- port code back into C# 8.0

I'm getting kinda involved with all this at this point, so I can help with the second one.

**Comment by FreyaHolmer** [comment]
I personally prefer to keep it up to date with newer C# versions - I want to treat it less like a backwards compatible public API and more like a personal math repository I use in my own projects, that happens to also be publicly available, mostly because it's easier that way (and what I'm doing in practice!)

**Comment by razenpok** [comment]
Fair enough, and I'm quite surprised that this repo got to 1.4k stars without a single issue created about backward compatibility
I'll add a 2021+ requirement to the package.json in the next PR 👌

**Comment by FreyaHolmer** [comment]
I suspect most of the new C# things were added only on the dev branch, not sure how many users are on dev at this point!
